name: gestura
description: "Application to translate Sign Language."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  google_fonts: ^6.3.2
  camera: ^0.11.3
  shared_preferences: ^2.2.2
  country_picker: ^2.0.20
  tflite_flutter: ^0.12.1
  google_mlkit_pose_detection: ^0.14.0
  google_mlkit_commons: ^0.11.0
  hand_landmarker: ^2.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/
  - assets/models/
  - assets/bisindo/
